// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcz2ijHsBl7dXqzL_xHb6Fh9sQ8SayqnY',
    appId: '1:406661054176:web:bef9e19e7763f0679f1a85',
    messagingSenderId: '406661054176',
    projectId: 'inputchecker',
    authDomain: 'inputchecker.firebaseapp.com',
    storageBucket: 'inputchecker.appspot.com',
    measurementId: 'G-PZ35Z4GKGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd2k5SUX2BZAOODgDbq3mn-P8pkDI_CNo',
    appId: '1:406661054176:android:e5d6c851185466439f1a85',
    messagingSenderId: '406661054176',
    projectId: 'inputchecker',
    storageBucket: 'inputchecker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmJPct_dflo7cCBBgD_h9Kbr8DRgOkUMc',
    appId: '1:406661054176:ios:8b18d07fd27eb1589f1a85',
    messagingSenderId: '406661054176',
    projectId: 'inputchecker',
    storageBucket: 'inputchecker.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmJPct_dflo7cCBBgD_h9Kbr8DRgOkUMc',
    appId: '1:406661054176:ios:8b18d07fd27eb1589f1a85',
    messagingSenderId: '406661054176',
    projectId: 'inputchecker',
    storageBucket: 'inputchecker.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcz2ijHsBl7dXqzL_xHb6Fh9sQ8SayqnY',
    appId: '1:406661054176:web:47e4a931b672f4e29f1a85',
    messagingSenderId: '406661054176',
    projectId: 'inputchecker',
    authDomain: 'inputchecker.firebaseapp.com',
    storageBucket: 'inputchecker.appspot.com',
    measurementId: 'G-VQKQZHMGP2',
  );
}
